config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:create, :index, :new, :show] do
  resources :reviews, only: [:new, :create]
 end
 root to: 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, :address, :category, presence: true
  validates_inclusion_of :category, in: CATEGORIES
end

app/models/review.rb
class Review < ApplicationRecord
   belongs_to :restaurant
   validates :content, :rating, presence: true
   validates :rating, numericality: {
  	only_integer: true,
  	greater_than_or_equal_to: 0,
  	less_than_or_equal_to: 5
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  	@restaurants = Restaurant.all 
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  	@reviews = @restaurant.reviews
  end

  def new
  	@restaurant = Restaurant.new
  end

  def create
  	@restaurant = Restaurant.new(restaurant_params)
  if restaurant.save
  	redirect_to @restaurant, notice: 'new restaurant created'
  else 
  	render :new
  end
end
  
  def address
  end
  
  private

  def restaurant_params
  	params.require(:restaurant).permit(:name, :address, :phone_category, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/application.html.erb
<head>
  <!-- ... -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

app/views/restaurants/index.html.erb
<div class="container">
	<div class="d-flex justify-content-between align-items-center py-6">
		<h1>Restaurants</h1>
		 <% link_to "Add restaurant", new_restaurant_path, class: 'btn btn-primary' %>
	</div>

<div class="row">
  <% @restaurants.each do |restaurant| %>
    <div class="col-4">
    	<div class="card">
    		<div class="card-body">
    			<h1> <%= restaurant.name%></h1>
    			 <p> <%= restaurant.address %></p>
    			 <%= link_to "details", restaurant_path(restaurant) %>
    		</div>
    	</div>
    </div>
	  <% end %>
	</div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
	<h1>New Restaurant</h1>

	<%= simple_form_for(@restaurant) do |f| %>
	<%= f.input :name %>
	<%= f.input :address %>
	<%= f.input :phone_number %>
	<%= f.input :category, as: :select, collection: Restaurant::CATEGORIES %>
	<%= f.submit 'Save Restaurant', class: "betn btn-primary" %>
 <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
	<h1><%= @restaurant.name %></h1>
	<p class="lead text-muted">
		<%= @restaurant.address %>
		<span class="badge badge-success">
			<%= @restaurant.category %>
		</span>
	</p>
<hr>
 <div class="d-flex justify-content-between  align-items-center">
 	<h2>
 		Reviews :
 	</h2>
 	<% link_to 'Add a Review', new_restaurant_path_review_path(@restaurant), class: 'btn btn-primary'%>
 </div>
  <ul class="list-group">
 	 <% @reviews.each do |review| %>
 	  <li>
 	  	<% review.content%>
 	  	<p class="small text-muted">
 	  		<% review.created_at%>
 	   </p>
 	  </li>
 	  <% end %>
   </div>
  </ul>
	</div>
</div>